#ifndef POINTER_PRAC_H_INCLUDED,MALLOC_PRAC_H_INCLUDED
#define POINTER_PRAC_H_INCLUDED,MALLOC_PRAC_H_INCLUDED
//#ifndef MALLOC_PRAC_H_INCLUDED
//#define MALLOC_PRAC_H_INCLUDED

int mallocfn();

int newmain();

#endif // POINTER_PRAC_H_INCLUDED
